### ISSUE TITLE
Missing function defintion for validateProcessSpec

### ISSUE THREAD

**Issue by galaxyblack** [gotoz/runq#1]
Beacuse of this missing function, `runq` can not compile.

**Comment by pmorjan** [comment]
The runq binary must be built inside the RunC source code tree where the function validateProcessSpec is defined. It's all done automatically by the Makefile.

**Comment by galaxyblack** [comment]
I see, would this be worth adding to the Makefile? Itd just be a git pull right?

**Comment by pmorjan** [comment]
You just have to follow the  [build instructions]( https://github.com/gotoz/runq#developing-runq).
And if you don't then the Makefile already fails with an useful error message:
```
Error: RunC source not found
To download RunC source: "go get -d github.com/opencontainers/runc"
 ```
The build setup is already complicated. I prefer to keep it as it is with no extra "silent download magic". Thanks.
