### ISSUE TITLE
labels instead of RUNQ_ envs

### ISSUE THREAD

**Issue by matti** [gotoz/runq#21]
What about using docker labels instead of RUNQ_ envs - this would allow docker images to specify requirements as

```
LABEL runq.cpu=2
LABEL runq.mem=2048
```

**Comment by pmorjan** [comment]
I don't think that this would be a good idea. Those env variables are used to specify the behavior of running containers and not the properties of images. Attributes like number of CPU or memory size do not belong to images.

**Comment by matti** [comment]
agreed
