### ISSUE TITLE
runc create failed: unsupported spec (1.1.0), need 1.0.x: unknown

### ISSUE THREAD

**Issue by sammcj** [gotoz/runq#29]
**Brief description**

After installing and configuring runq, 

```
docker run --runtime runq -ti busybox sh
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unsupported spec (1.1.0), need 1.0.x: unknown.
ERRO[0000] error waiting for container: context canceled
```

However my installed runc version (1.1.11) has a valid spec of 1.0.2-dev:

```
runc --version
runc version 1.1.11
commit: v1.1.11-0-g4bccb38
spec: 1.0.2-dev
go: go1.20.13
libseccomp: 2.5.3
```

Fedora 39

**Steps to reproduce the issue**

- Start with a Fedora 39 base system
- Install Docker and runc
- Follow runq install instructions
- Run busybox sh with runq runtime

**Expected behaviour**

runq to work and not have issues with runc

**Actual behaviour**

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unsupported spec (1.1.0), need 1.0.x: unknown.

**Content of section `runtimes` of `/etc/docker/daemon.json`**

```
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        },
        "runq": {
          "path":"/var/lib/runq/runq",
          "runtimeArgs": [
            "--cpu", "4",
            "--mem", "512",
            "--dns", "192.168.0.1",
            "--tmpfs", "/tmp"
          ]
      }
    },
```

**Content of `/var/lib/runq/qemu/proxy --version`**

6157535+ (go1.21.6)

**Content of `docker --version`**

Docker version 25.0.1, build 29cf629

**Additional information**

**Comment by pmorjan** [comment]
can you please provide the output of 
```
/var/lib/runq/runq --version
```

**Comment by sammcj** [comment]
```
runc version 1.1.11
commit: v1.1.11-0-g4bccb38c-dirty
spec: 1.0.2-dev
go: go1.21.6
```

**Comment by pmorjan** [comment]
please try latest version

**Comment by sammcj** [comment]
That fixed it!

Thanks a bunch 😄 

```
docker run --runtime runq -ti busybox sh
/ # whoami
root
```
