### ISSUE TITLE
Support for RHEL

### ISSUE THREAD

**Issue by NiranjanUv** [gotoz/runq#32]
**Brief description**
Is there any plan to support for RHEL ?

**Steps to reproduce the issue**

**Expected behaviour**

**Actual behaviour**

**Content of section `runtimes` of `/etc/docker/daemon.json`**

**Content of `/var/lib/runq/qemu/proxy --version`**

**Content of `docker --version`**

**Additional information**

**Comment by pmorjan** [comment]
No.
