### ISSUE TITLE
Can runq be compiled & run on Mac OS X without QEMU?

### ISSUE THREAD

**Issue by amorphid** [gotoz/runq#5]
It wasn't clear to me from the README.  If the answer is no, I'll stop trying to install it on my Mac :)  If they answer is yes, I'll submit a bug report.  Since it's runc based, I'm guessing the answer is no.

EDIT:  Changed title from `Should runq be usable on Mac OS X?` to `Can runq be compiled & run on Mac OS X without QEMU?`

**Comment by pmorjan** [comment]
You are right. The answer is no. The host must be a regular Linux system that is capable of running Qemu/KVM guests.

**Comment by prologic** [comment]
> You are right. The answer is no. The host must be a regular Linux system that is capable of running Qemu/KVM guests.

I don't understand this actually. macOS _can_ in fact run QEMU/KVm guests. Its as simple as installing `qemu` with `brew install qemu` and running it like anything else. What am I missing here?

**Comment by amorphid** [comment]
@prologic I was looking into whether I could compile & run it directly on MacOS w/o QEMU, and the answer was no.  I updated the title to be more clear about that.
